- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/terminal.yml
    - import_tasks: tasks/winmanager.yml
