- name: Create personal user
  ansible.builtin.user:
    name: "{{ username }}"
    create_home: True
    shell: /bin/zsh
    state: present

- name: Add user to sudoers
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ username }}"
    content: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
