- name: Install and configure Window Manager + background
  ansible.builtin.apt: 
    name: "{{ item }}"
  loop:
    - rofi
    - feh
    - i3

- name: Ensure that pic and rofi folders exist
  ansible.builtin.file:
    path: "/home/{{ username }}/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - Pictures
    - .local/share/rofi/themes
    - .config/rofi

- name: Download wallpaper
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxdotexe/nordic-wallpapers/HEAD/wallpapers/ign-0011.png
    dest: "/home/{{ username }}/Pictures/default.png"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create wallpaper symlink
  ansible.builtin.file:
    src: "/home/{{ username }}/Pictures/default.png"
    dest: "/home/{{ username }}/Pictures/wallpaper.png"
    state: link
    owner: "{{ username }}"
    group: "{{ username }}"
    follow: false

- name: Set rofi theme
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/rofi/config.rasi"
    content: '@theme "/home/{{ username }}/.local/share/rofi/themes/nord.rasi"'
