- name: Install and configure Window Manager + background
  ansible.builtin.apt: 
    name: "{{ item }}"
  loop:
    - rofi
    - feh
    - i3

- name: Ensure that pic and rofi folders exist
  ansible.builtin.file:
    path: "/home/orenga/{{ item }}"
    state: directory
    owner: orenga
    group: orenga
  loop:
    - Pictures
    - .local/share/rofi/themes
    - .config/rofi

- name: Download wallpaper
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxdotexe/nordic-wallpapers/HEAD/wallpapers/ign-0011.png
    dest: /home/orenga/Pictures/default.png
    owner: orenga
    group: orenga

- name: Create wallpaper symlink
  ansible.builtin.file:
    src: /home/orenga/Pictures/default.png
    dest: /home/orenga/Pictures/wallpaper.png
    state: link
    owner: orenga
    group: orenga
    follow: false

- name: Set rofi theme
  ansible.builtin.copy:
    dest: /home/orenga/.config/rofi/config.rasi
    content: '@theme "/home/orenga/.local/share/rofi/themes/nord.rasi"'
